import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { ArrowLeft, CreditCard, Landmark, LogOut, MoreHorizontal, Pencil, Plus, Search, Trash2, TrendingUp, UserRound } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { computeLoanWithPayments, formatBRL, formatDate, type Loan, type Payment, type Person } from "@/lib/loans";
import { LoanFormDialog, type LoanFormValues } from "@/components/LoanFormDialog";
import { ThemeToggle } from "@/components/ThemeToggle";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";

export const Route = createFileRoute("/_authenticated/painel")({ component: Dashboard });
type DeleteTarget = { kind: "person"; item: Person } | { kind: "loan"; item: Loan } | { kind: "payment"; item: Payment };

function Dashboard() {
  const { session } = useAuth(); const qc = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null); const [search, setSearch] = useState("");
  const [personOpen, setPersonOpen] = useState(false); const [editingPerson, setEditingPerson] = useState<Person | null>(null); const [personName, setPersonName] = useState(""); const [personEmail, setPersonEmail] = useState(""); const [personPhone, setPersonPhone] = useState(""); const [personNotes, setPersonNotes] = useState("");
  const [loanOpen, setLoanOpen] = useState(false); const [editingLoan, setEditingLoan] = useState<Loan | null>(null); const [loanPersonId, setLoanPersonId] = useState("");
  const [payingLoan, setPayingLoan] = useState<Loan | null>(null); const [payAmount, setPayAmount] = useState(""); const [payDate, setPayDate] = useState(new Date().toISOString().slice(0, 10)); const [payNotes, setPayNotes] = useState("");
  const [deleting, setDeleting] = useState<DeleteTarget | null>(null);
  const { data: people = [], isLoading } = useQuery({ queryKey: ["people"], queryFn: async () => { const { data, error } = await supabase.from("people").select("*").order("name"); if (error) throw error; return data as Person[]; } });
  const { data: loans = [] } = useQuery({ queryKey: ["loans"], queryFn: async () => { const { data, error } = await supabase.from("loans").select("*").order("loan_date", { ascending: false }); if (error) throw error; return data as Loan[]; } });
  const { data: payments = [] } = useQuery({ queryKey: ["payments"], queryFn: async () => { const { data, error } = await supabase.from("payments").select("*").order("payment_date", { ascending: false }); if (error) throw error; return data as Payment[]; } });
  const refresh = () => Promise.all([qc.invalidateQueries({ queryKey: ["people"] }), qc.invalidateQueries({ queryKey: ["loans"] }), qc.invalidateQueries({ queryKey: ["payments"] })]);
  const today = new Date(); const selected = people.find((p) => p.id === selectedId) ?? null;
  const allRows = useMemo(() => loans.map((loan) => ({ loan, ...computeLoanWithPayments(loan, payments, today) })), [loans, payments]); // eslint-disable-line react-hooks/exhaustive-deps
  const rows = allRows.filter((r) => r.loan.person_id === selectedId);
  const sum = (rs: typeof allRows) => rs.reduce((a, r) => ({ original: a.original + Number(r.loan.principal_amount), calculated: a.calculated + r.amount, paid: a.paid + r.paid, balance: a.balance + r.balance, interest: a.interest + r.interest }), { original: 0, calculated: 0, paid: 0, balance: 0, interest: 0 });
  const globalTotals = sum(allRows); const totals = sum(rows);
  const openPerson = (p?: Person) => { setEditingPerson(p ?? null); setPersonName(p?.name ?? ""); setPersonEmail(p?.email ?? ""); setPersonPhone(p?.phone ?? ""); setPersonNotes(p?.notes ?? ""); setPersonOpen(true); };
  const savePerson = async () => { const name = personName.trim(); if (!name) return toast.error("Informe o nome da pessoa."); const payload = { name, email: personEmail.trim() || null, phone: personPhone.trim() || null, notes: personNotes.trim() || null }; const { error } = editingPerson ? await supabase.from("people").update(payload).eq("id", editingPerson.id) : await supabase.from("people").insert({ ...payload, user_id: session!.user.id }); if (error) return toast.error("Não foi possível salvar a pessoa."); setPersonOpen(false); toast.success(editingPerson ? "Pessoa atualizada" : "Pessoa adicionada"); await refresh(); };
  const openNewLoan = (personId = "") => { setEditingLoan(null); setLoanPersonId(personId); setLoanOpen(true); };
  const saveLoan = async (v: LoanFormValues) => { const personId = editingLoan?.person_id ?? (selected?.id || loanPersonId); if (!personId) return toast.error("Selecione a pessoa do empréstimo."); const payload = { ...v, notes: v.notes || null, person_id: personId }; const { error } = editingLoan ? await supabase.from("loans").update(payload).eq("id", editingLoan.id) : await supabase.from("loans").insert({ ...payload, user_id: session!.user.id }); if (error) return toast.error("Não foi possível salvar o empréstimo."); setLoanOpen(false); toast.success(editingLoan ? "Empréstimo atualizado" : "Empréstimo adicionado"); await refresh(); };
  const openPayment = (loan: Loan, settle = false) => { const row = allRows.find((r) => r.loan.id === loan.id); setPayingLoan(loan); setPayAmount(settle && row ? row.balance.toFixed(2) : ""); setPayDate(new Date().toISOString().slice(0, 10)); setPayNotes(""); };
  const savePayment = async () => { if (!payingLoan) return; const amount = Number(payAmount); const row = allRows.find((r) => r.loan.id === payingLoan.id); if (!Number.isFinite(amount) || amount <= 0) return toast.error("Informe um valor válido."); if (!row || amount > row.balance + .005) return toast.error("O pagamento não pode ser maior que o saldo atual."); const { error } = await supabase.from("payments").insert({ user_id: session!.user.id, loan_id: payingLoan.id, amount, payment_date: payDate, notes: payNotes.trim() || null }); if (error) return toast.error("Não foi possível registrar o pagamento."); if (amount >= row.balance - .005) await supabase.from("loans").update({ status: "paid" }).eq("id", payingLoan.id); setPayingLoan(null); toast.success(amount >= row.balance - .005 ? "Empréstimo liquidado" : "Pagamento registrado"); await refresh(); };
  const remove = async () => { if (!deleting) return; const table = deleting.kind === "person" ? "people" : deleting.kind === "loan" ? "loans" : "payments"; const { error } = await supabase.from(table).delete().eq("id", deleting.item.id); if (error) return toast.error("Não foi possível excluir."); if (deleting.kind === "person") setSelectedId(null); setDeleting(null); toast.success("Registro excluído"); await refresh(); };
  const filteredPeople = people.filter((p) => p.name.toLowerCase().includes(search.trim().toLowerCase()));

  return <div className="min-h-screen"><Header email={session?.user.email}/><main className="mx-auto max-w-7xl space-y-7 px-4 py-6 sm:px-6 sm:py-8">
    {!selected ? <>
      <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-muted-foreground">Atualizado em {today.toLocaleDateString("pt-BR")}</p><h1 className="font-display text-4xl">Seus empréstimos</h1></div><Button type="button" size="sm" className="gap-1.5 pl-2.5 pr-3" onClick={() => people.length ? openNewLoan() : openPerson()}><Plus className="h-4 w-4"/> Novo empréstimo</Button></div>
      <section className="grid gap-4 md:grid-cols-3"><Summary label="Total original emprestado" value={formatBRL(globalTotals.original)} hint={`${loans.length} empréstimo(s)`}/><Summary label="Total atualizado com juros" value={formatBRL(globalTotals.calculated)} hint={`Recebido: ${formatBRL(globalTotals.paid)}`}/><div className="bg-hero rounded-xl p-6 text-primary-foreground shadow-card dark:text-foreground"><div className="flex items-center justify-between text-sm opacity-80">Total de juros acumulados <TrendingUp className="h-4 w-4"/></div><div className="tabular mt-3 text-3xl font-semibold">{formatBRL(globalTotals.interest)}</div><div className="mt-3 text-xs opacity-80">Saldo a receber: {formatBRL(globalTotals.balance)}</div></div></section>
      <section className="rounded-xl border bg-card shadow-card"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative sm:w-72"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar pessoa..." value={search} onChange={(e) => setSearch(e.target.value)}/></div><Button variant="outline" onClick={() => openPerson()}><UserRound className="h-4 w-4"/> Nova pessoa</Button></div>
        {isLoading ? <div className="p-12 text-center text-muted-foreground">Carregando...</div> : filteredPeople.length === 0 ? <div className="p-12 text-center text-muted-foreground">Nenhuma pessoa cadastrada. Adicione uma pessoa para começar.</div> : <div className="divide-y">{filteredPeople.map((p) => { const prs = allRows.filter((r) => r.loan.person_id === p.id); const pt = sum(prs); return <div key={p.id} role="button" tabIndex={0} onClick={() => setSelectedId(p.id)} onKeyDown={(e) => e.key === "Enter" && setSelectedId(p.id)} className="flex cursor-pointer items-center justify-between gap-4 p-4 transition hover:bg-muted/40"><div className="flex min-w-0 items-center gap-3"><div className="rounded-full bg-secondary p-2"><UserRound className="h-5 w-5"/></div><div className="min-w-0"><div className="truncate font-semibold">{p.name}</div><div className="text-xs text-muted-foreground">{prs.length} empréstimo(s) · A receber {formatBRL(pt.balance)}</div></div></div><div className="flex items-center gap-2"><div className="hidden text-right sm:block"><div className="text-xs text-muted-foreground">Total com juros</div><div className="tabular font-semibold">{formatBRL(pt.calculated)}</div></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" onClick={(e) => e.stopPropagation()}><MoreHorizontal className="h-4 w-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={(e) => { e.stopPropagation(); openPerson(p); }}><Pencil className="h-4 w-4"/>Editar pessoa</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem className="text-destructive" onClick={(e) => { e.stopPropagation(); setDeleting({ kind: "person", item: p }); }}><Trash2 className="h-4 w-4"/>Excluir pessoa</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div>; })}</div>}
      </section>
    </> : <>
      <div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" onClick={() => setSelectedId(null)}><ArrowLeft className="h-5 w-5"/></Button><div><p className="text-sm text-muted-foreground">Cliente</p><h1 className="font-display text-3xl sm:text-4xl">{selected.name}</h1></div></div><div className="flex gap-2"><Button variant="outline" onClick={() => openPerson(selected)}><Pencil className="h-4 w-4"/> Editar</Button><Button size="sm" className="gap-1.5 pl-2.5 pr-3" onClick={() => openNewLoan(selected.id)}><Plus className="h-4 w-4"/> Novo empréstimo</Button></div></div>
      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Total original" value={formatBRL(totals.original)} hint={`${rows.length} empréstimo(s)`}/><Summary label="Calculado com juros" value={formatBRL(totals.calculated)} hint="Antes dos pagamentos"/><Summary label="Já recebido" value={formatBRL(totals.paid)} hint="Pagamentos registrados"/><div className="bg-hero rounded-xl p-5 text-primary-foreground shadow-card dark:text-foreground"><div className="text-sm opacity-80">Saldo a receber</div><div className="tabular mt-2 text-3xl font-semibold">{formatBRL(totals.balance)}</div><div className="mt-2 text-xs opacity-80">Juros gerados: {formatBRL(totals.interest)}</div></div></section>
      <section className="space-y-4">{rows.length === 0 ? <div className="rounded-xl border bg-card p-12 text-center text-muted-foreground">Nenhum empréstimo para {selected.name}.</div> : rows.map((r) => <LoanCard key={r.loan.id} row={r} payments={payments.filter((p) => p.loan_id === r.loan.id)} onPay={() => openPayment(r.loan)} onSettle={() => openPayment(r.loan, true)} onEdit={() => { setEditingLoan(r.loan); setLoanPersonId(r.loan.person_id); setLoanOpen(true); }} onDelete={() => setDeleting({ kind: "loan", item: r.loan })} onDeletePayment={(p) => setDeleting({ kind: "payment", item: p })}/>)}</section>
    </>}
  </main>
  <Dialog open={personOpen} onOpenChange={setPersonOpen}><DialogContent className="w-[calc(100%-2rem)] max-w-md rounded-lg"><DialogHeader><DialogTitle>{editingPerson ? "Editar pessoa" : "Nova pessoa"}</DialogTitle></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Nome</Label><Input value={personName} onChange={(e) => setPersonName(e.target.value)} autoFocus/></div><div className="space-y-2"><Label>Email (opcional)</Label><Input type="email" value={personEmail} onChange={(e) => setPersonEmail(e.target.value)}/></div><div className="space-y-2"><Label>Telefone (opcional)</Label><Input type="tel" value={personPhone} onChange={(e) => setPersonPhone(e.target.value)}/></div><div className="space-y-2"><Label>Observações (opcional)</Label><Textarea value={personNotes} onChange={(e) => setPersonNotes(e.target.value)}/></div></div><DialogFooter><Button variant="ghost" onClick={() => setPersonOpen(false)}>Cancelar</Button><Button onClick={savePerson}>Salvar</Button></DialogFooter></DialogContent></Dialog>
  <LoanFormDialog open={loanOpen} onOpenChange={setLoanOpen} loan={editingLoan} personName={editingLoan ? people.find((p) => p.id === editingLoan.person_id)?.name : selected?.name} people={!selected && !editingLoan ? people : undefined} personId={loanPersonId} onPersonChange={setLoanPersonId} onSubmit={saveLoan}/>
  <Dialog open={!!payingLoan} onOpenChange={(o) => !o && setPayingLoan(null)}><DialogContent><DialogHeader><DialogTitle>Registrar pagamento</DialogTitle></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Valor pago (R$)</Label><Input type="number" min="0.01" step="0.01" value={payAmount} onChange={(e) => setPayAmount(e.target.value)}/></div><div className="space-y-2"><Label>Data</Label><Input type="date" value={payDate} onChange={(e) => setPayDate(e.target.value)}/></div><div className="space-y-2"><Label>Observação</Label><Textarea value={payNotes} onChange={(e) => setPayNotes(e.target.value)}/></div></div><DialogFooter><Button variant="ghost" onClick={() => setPayingLoan(null)}>Cancelar</Button><Button onClick={savePayment}>Registrar</Button></DialogFooter></DialogContent></Dialog>
  <AlertDialog open={!!deleting} onOpenChange={(o) => !o && setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir registro?</AlertDialogTitle><AlertDialogDescription>{deleting?.kind === "person" ? "A pessoa, seus empréstimos e pagamentos serão removidos permanentemente." : "Esta ação é permanente e os totais serão recalculados."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground" onClick={remove}>Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
function Header({ email }: { email?: string }) { return <header className="border-b bg-card/60 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><div className="flex items-center gap-2 font-semibold"><Landmark className="h-5 w-5 text-primary"/>Juros Diários</div><div className="flex items-center gap-1"><span className="mr-2 hidden text-sm text-muted-foreground sm:inline">{email}</span><ThemeToggle/><Button variant="ghost" size="icon" onClick={() => supabase.auth.signOut()}><LogOut className="h-4 w-4"/></Button></div></div></header>; }
function Summary({ label, value, hint }: { label: string; value: string; hint: string }) { return <div className="rounded-xl border bg-card p-5 shadow-card"><div className="text-sm text-muted-foreground">{label}</div><div className="tabular mt-2 text-2xl font-semibold">{value}</div><div className="mt-2 text-xs text-muted-foreground">{hint}</div></div>; }
function LoanCard({ row, payments, onPay, onSettle, onEdit, onDelete, onDeletePayment }: { row: ReturnType<typeof computeLoanWithPayments> & { loan: Loan }; payments: Payment[]; onPay: () => void; onSettle: () => void; onEdit: () => void; onDelete: () => void; onDeletePayment: (p: Payment) => void }) { const { loan } = row; const elapsed = `${row.fullMonths} ${row.fullMonths === 1 ? "mês" : "meses"} ${row.remainingDays} ${row.remainingDays === 1 ? "dia" : "dias"}`; return <div className="rounded-xl border bg-card p-4 shadow-card sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="font-semibold">Empréstimo de {formatDate(loan.loan_date)}</span><Badge variant={row.balance <= .005 ? "secondary" : "outline"}>{row.balance <= .005 ? "Quitado" : "Ativo"}</Badge></div><div className="mt-1 text-xs text-muted-foreground">{elapsed} · {Number(loan.interest_rate).toLocaleString("pt-BR")}% {loan.rate_period === "monthly" ? "a.m." : "a.a."}</div></div><div className="flex flex-wrap gap-2">{row.balance > .005 && <><Button size="sm" onClick={onPay}><CreditCard className="h-4 w-4"/> Registrar pagamento</Button><Button size="sm" variant="outline" onClick={onSettle}>Liquidar</Button></>}<DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon"><MoreHorizontal className="h-4 w-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={onEdit}><Pencil className="h-4 w-4"/>Editar</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem className="text-destructive" onClick={onDelete}><Trash2 className="h-4 w-4"/>Excluir</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div><div className="mt-5 grid grid-cols-2 gap-4 text-sm sm:grid-cols-5"><Metric label="Original" value={formatBRL(Number(loan.principal_amount))}/><Metric label="Juros" value={`+${formatBRL(row.interest)}`} success/><Metric label="Calculado" value={formatBRL(row.amount)}/><Metric label="Já pago" value={formatBRL(row.paid)}/><Metric label="Saldo" value={formatBRL(row.balance)} strong/></div>{payments.length > 0 && <div className="mt-5 border-t pt-4"><div className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Histórico de pagamentos</div><div className="space-y-2">{payments.map((p) => <div key={p.id} className="flex items-center justify-between gap-3 rounded-lg bg-muted/50 px-3 py-2 text-sm"><div><span className="tabular font-medium">{formatBRL(Number(p.amount))}</span><span className="ml-2 text-muted-foreground">{formatDate(p.payment_date)}{p.notes ? ` · ${p.notes}` : ""}</span></div><Button variant="ghost" size="icon" onClick={() => onDeletePayment(p)}><Trash2 className="h-3.5 w-3.5"/></Button></div>)}</div></div>}</div>; }
function Metric({ label, value, success, strong }: { label: string; value: string; success?: boolean; strong?: boolean }) { return <div><div className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</div><div className={`tabular mt-1 ${success ? "text-success" : ""} ${strong ? "font-bold" : "font-medium"}`}>{value}</div></div>; }
